IF OBJECT_ID('Enrolment') IS NOT NULL
DROP TABLE Enrolment;
IF OBJECT_ID('SubjectOffering') IS NOT NULL
DROP TABLE SubjectOffering;
IF OBJECT_ID('Student') IS NOT NULL
DROP TABLE Student;
IF OBJECT_ID('Teacher') IS NOT NULL
DROP TABLE Teacher;
IF OBJECT_ID('STUDENT') IS NOT NULL
DROP TABLE STUDENT;
IF OBJECT_ID('SUBJECT') IS NOT NULL
DROP TABLE SUBJECT;


GO
